# Generated by Django 5.2.1 on 2025-06-02 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IR_yearly', models.IntegerField(default=0)),
                ('IR_monthly', models.IntegerField(default=0)),
                ('TR_yearly', models.IntegerField(default=0)),
                ('TR_monthly', models.IntegerField(default=0)),
                ('EN_yearly', models.IntegerField(default=0)),
                ('EN_monthly', models.IntegerField(default=0)),
                ('token1M', models.IntegerField(default=0)),
                ('token3M', models.IntegerField(default=0)),
                ('token5M', models.IntegerField(default=0)),
                ('token10M', models.IntegerField(default=0)),
                ('email1K', models.IntegerField(default=0)),
                ('email3K', models.IntegerField(default=0)),
                ('email5K', models.IntegerField(default=0)),
                ('email10K', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
