services:

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django_app
    #command: python src/manage.py runserver 0.0.0.0:443
    command: gunicorn src.wsgi:application --bind 0.0.0.0:443

    volumes:
      - ./src:/app
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - "443:443"
    env_file:
      - .env
    depends_on:
      - db
      - redis

  db:
    image: postgres:15
    container_name: postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  redis:
    image: redis:7
    container_name: redis_cache
    ports:
      - "6379:6379"

volumes:
  postgres_data:
  static_volume:
  media_volume: