version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django_app
    command: python src/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./src:/app
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis

  db:
    image: postgres:15
    container_name: postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: your_db_name
      POSTGRES_USER: your_user
      POSTGRES_PASSWORD: your_password

  redis:
    image: redis:7
    container_name: redis_cache
    ports:
      - "6379:6379"

volumes:
  postgres_data:
  static_volume:
  media_volume:
