name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:

  test:
    name: Run Tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: FikoUsr
          POSTGRES_PASSWORD: FikoPass123!!!
          POSTGRES_DB: FikoDB
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r src/requirements/development.txt 

      - name: Run tests
        run: |
          MANAGE_PATH=$(find . -name manage.py -exec dirname {} \;)
          cd $MANAGE_PATH
          python manage.py test
        env:
          STAGE: "DEV"
          DEBUG: True
          SECRET_KEY: "jango-insecure-_#2hxi#d@7!6bg((p@tmy-)#y3i_ad=n!pm4@_h2c60+1m9gty"
          DJANGO_ALLOWED_HOSTS: "*"
          POSTGRES_DB: "FikoDB"
          POSTGRES_USER: "FikoUsr"
          POSTGRES_PASSWORD: "FikoPass123!!!"
          POSTGRES_HOST: "localhost"
          POSTGRES_PORT: 5432
          REDIS_URL: "redis://redis:6379/0"


  deploy:
    name: Deploy to AWS EC2
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH key
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}

    - name: Add EC2 to known hosts
      run: |
        ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

    - name: Copy files to EC2
      run: |
        rsync -avz --exclude '.git' --exclude '__pycache__' --exclude '.github' ./ ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/home/ubuntu/fiko-backend

    - name: SSH and deploy on EC2
      run: |
        ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          cd /home/ubuntu/fiko-backend
          docker-compose down
          docker-compose pull
          docker-compose build
          docker-compose up -d --remove-orphans
        EOF