name: Deploy to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@your-ec2-public-ip << 'EOF'
          cd /home/ubuntu/app
          git pull origin main
          docker stop app || true && docker rm app || true
          docker build -t app .
          docker run -d -p 8000:8000 --name app app
        EOF
